src/Entity/Retour.php
<?php

namespace App\Entity;

use App\Entity\RetourProduit;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\RetourRepository;
use App\Entity\RetourProduitReceptionnes;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: RetourRepository::class)]
class Retour
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $num_retour = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_autorisation = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $nom_client = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $prenom_client = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $transporteur = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_traitement = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $etat = null;

    #[ORM\Column(length: 500, nullable: true)]
    private ?string $commentaire = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $photo_1 = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $photo_2 = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $photo_3 = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $photo_4 = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $photo_5 = null;

    #[ORM\OneToMany(mappedBy: 'retour', targetEntity: RetourProduit::class)]
    private Collection $retourProduits;

    #[ORM\OneToMany(mappedBy: 'retour', targetEntity: RetourProduitReceptionnes::class)]
    private Collection $retourProduitReceptionnes;

    #[ORM\ManyToOne(inversedBy: 'retours')]
    private ?Bordereau $bordereau = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $etat_produit = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $etat_02 = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $etat_produit_02 = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $etat_03 = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $etat_produit_03 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $commentaire_autorisation = null;

    public function __construct()
    {
        $this->retourProduits = new ArrayCollection();
        $this->retourProduitReceptionnes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumRetour(): ?string
    {
        return $this->num_retour;
    }

    public function setNumRetour(?string $num_retour): static
    {
        $this->num_retour = $num_retour;

        return $this;
    }

    public function getDateAutorisation(): ?\DateTimeInterface
    {
        return $this->date_autorisation;
    }

    public function setDateAutorisation(?\DateTimeInterface $date_autorisation): static
    {
        $this->date_autorisation = $date_autorisation;

        return $this;
    }

    public function getNomClient(): ?string
    {
        return $this->nom_client;
    }

    public function setNomClient(?string $nom_client): static
    {
        $this->nom_client = $nom_client;

        return $this;
    }

    public function getPrenomClient(): ?string
    {
        return $this->prenom_client;
    }

    public function setPrenomClient(?string $prenom_client): static
    {
        $this->prenom_client = $prenom_client;

        return $this;
    }

    public function getTransporteur(): ?string
    {
        return $this->transporteur;
    }

    public function setTransporteur(?string $transporteur): static
    {
        $this->transporteur = $transporteur;

        return $this;
    }

    public function getDateTraitement(): ?\DateTimeInterface
    {
        return $this->date_traitement;
    }

    public function setDateTraitement(?\DateTimeInterface $date_traitement): static
    {
        $this->date_traitement = $date_traitement;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(?string $etat): static
    {
        $this->etat = $etat;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getPhoto1(): ?string
    {
        return $this->photo_1;
    }

    public function setPhoto1(?string $photo_1): static
    {
        $this->photo_1 = $photo_1;

        return $this;
    }

    public function getPhoto2(): ?string
    {
        return $this->photo_2;
    }

    public function setPhoto2(?string $photo_2): static
    {
        $this->photo_2 = $photo_2;

        return $this;
    }

    public function getPhoto3(): ?string
    {
        return $this->photo_3;
    }

    public function setPhoto3(?string $photo_3): static
    {
        $this->photo_3 = $photo_3;

        return $this;
    }

    public function getPhoto4(): ?string
    {
        return $this->photo_4;
    }

    public function setPhoto4(?string $photo_4): static
    {
        $this->photo_4 = $photo_4;

        return $this;
    }

    public function getPhoto5(): ?string
    {
        return $this->photo_5;
    }

    public function setPhoto5(?string $photo_5): static
    {
        $this->photo_5 = $photo_5;

        return $this;
    }

    /**
     * @return Collection<int, RetourProduit>
     */
    public function getRetourProduits(): Collection
    {
        return $this->retourProduits;
    }

    public function addRetourProduit(RetourProduit $retourProduit): static
    {
        if (!$this->retourProduits->contains($retourProduit)) {
            $this->retourProduits->add($retourProduit);
            $retourProduit->setRetour($this);
        }

        return $this;
    }

    public function removeRetourProduit(RetourProduit $retourProduit): static
    {
        if ($this->retourProduits->removeElement($retourProduit)) {
            // set the owning side to null (unless already changed)
            if ($retourProduit->getRetour() === $this) {
                $retourProduit->setRetour(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RetourProduitReceptionnes>
     */
    public function getRetourProduitReceptionnes(): Collection
    {
        return $this->retourProduitReceptionnes;
    }

    public function addRetourProduitReceptionne(RetourProduitReceptionnes $retourProduitReceptionne): static
    {
        if (!$this->retourProduitReceptionnes->contains($retourProduitReceptionne)) {
            $this->retourProduitReceptionnes->add($retourProduitReceptionne);
            $retourProduitReceptionne->setRetour($this);
        }

        return $this;
    }

    public function removeRetourProduitReceptionne(RetourProduitReceptionnes $retourProduitReceptionne): static
    {
        if ($this->retourProduitReceptionnes->removeElement($retourProduitReceptionne)) {
            // set the owning side to null (unless already changed)
            if ($retourProduitReceptionne->getRetour() === $this) {
                $retourProduitReceptionne->setRetour(null);
            }
        }

        return $this;
    }

    public function getBordereau(): ?Bordereau
    {
        return $this->bordereau;
    }

    public function setBordereau(?Bordereau $bordereau): static
    {
        $this->bordereau = $bordereau;

        return $this;
    }

    public function __toString()
    {
        return $this->num_retour;
    }

    public function getEtatProduit(): ?string
    {
        return $this->etat_produit;
    }

    public function setEtatProduit(string $etat_produit): static
    {
        $this->etat_produit = $etat_produit;

        return $this;
    }

    public function getEtat02(): ?string
    {
        return $this->etat_02;
    }

    public function setEtat02(?string $etat_02): static
    {
        $this->etat_02 = $etat_02;

        return $this;
    }

    public function getEtatProduit02(): ?string
    {
        return $this->etat_produit_02;
    }

    public function setEtatProduit02(?string $etat_produit_02): static
    {
        $this->etat_produit_02 = $etat_produit_02;

        return $this;
    }

    public function getEtat03(): ?string
    {
        return $this->etat_03;
    }

    public function setEtat03(?string $etat_03): static
    {
        $this->etat_03 = $etat_03;

        return $this;
    }

    public function getEtatProduit03(): ?string
    {
        return $this->etat_produit_03;
    }

    public function setEtatProduit03(?string $etat_produit_03): static
    {
        $this->etat_produit_03 = $etat_produit_03;

        return $this;
    }

    public function getCommentaireAutorisation(): ?string
    {
        return $this->commentaire_autorisation;
    }

    public function setCommentaireAutorisation(?string $commentaire_autorisation): static
    {
        $this->commentaire_autorisation = $commentaire_autorisation;

        return $this;
    }
}

src/Controller/ListeBordereauxController.php
<?php

namespace App\Controller;

use App\Entity\Retour;
use App\Entity\Bordereau;
use App\Form\SearchRetourType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ListeBordereauxController extends AbstractController
{

    private $csrfTokenManager;

    public function __construct(CsrfTokenManagerInterface $csrfTokenManager)
    {
        $this->csrfTokenManager = $csrfTokenManager;
    }

    #[IsGranted("ROLE_USER")]
    #[Route('/liste/bordereaux', name: 'app_liste_bordereaux')]
    public function index(Request $request, EntityManagerInterface $entityManager): Response
    {
        $bordereaux = $entityManager->getRepository(Bordereau::class)->findAll();

        $criteria = [];
        if (!empty($request->query->get('date_reception'))) {
            $dateReception = $request->query->get('date_reception');
            $dateTime = new \DateTime($dateReception);
            $formattedDate = $dateTime->format('Y-m-d H:i:s');
            $criteria['date_reception'] = $formattedDate;
            $bordereaux = $entityManager->getRepository(Bordereau::class)->findByDate($criteria);
        }

        $retours = $entityManager->getRepository(Retour::class)->findAll();

        $retourProduits = [];
        foreach ($retours as $retour) {
            $retourProduits = array_merge($retourProduits, $retour->getRetourProduits()->toArray());
        }

        $form = $this->createForm(SearchRetourType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $data = $form->getData();

            $criteria = [];
            if (!empty($data['numRetour'])) {
                $criteria['num_retour'] = $data['numRetour'];
            }

            if (!empty($data['prenomClient'])) {
                $criteria['prenom_client'] = $data['prenomClient'];
            }

            if (!empty($data['nomClient'])) {
                $criteria['nom_client'] = $data['nomClient'];
            }

            if (!empty($data['transporteur'])) {
                $criteria['transporteur'] = $data['transporteur'];
            }
            $retours = $entityManager->getRepository(Retour::class)->findByCriteria($criteria);
            
        } else {
            $retours = $entityManager->getRepository(Retour::class)->findAll();
        }

        if ($request->isMethod('GET') && !empty($request->query->get('bordereau')) && !empty($request->query->all('liste', []))) {
            $bordereauId = $request->query->get('bordereau');
            $linkedRetours = $request->query->all('liste', []);

            if ($bordereauId) {
                // Récupérer le Bordereau associé à l'ID
                $bordereau = $entityManager->getRepository(Bordereau::class)->find($bordereauId);

                // Vérifier si le Bordereau existe
                if ($bordereau) {
                    // Parcourir les Retours liés et associer le Bordereau à chaque Retour
                    foreach ($linkedRetours as $retourId) {
                        $retour = $entityManager->getRepository(Retour::class)->find($retourId);

                        // Vérifier si le Retour existe
                        if ($retour) {
                            // Définir le Bordereau associé au Retour
                            $retour->setBordereau($bordereau);
                            $retourToModified = $retour->getNumRetour();
                            $chaine = preg_replace('/^NT/', 'RETSA', $retourToModified);
                            $retour->setNumRetour($chaine);

                            // Enregistrer les modifications dans la base de données
                            $entityManager->persist($retour);
                        }
                    }

                    // Exécuter les modifications
                    $entityManager->flush();

                    $this->addFlash(
                        'notice',
                        'Le bordereau a bien été lié aux attendus ou sans attendus!'
                    );
                }
            }
        }

        $csrfTokenDateBordereau = $this->csrfTokenManager->getToken('form-date-bordereau');
        $csrfTokenLierBordereau = $this->csrfTokenManager->getToken('form-lier-bordereau');

        return $this->render('liste_bordereaux/index.html.twig', [
            'controller_name' => 'ListeBordereauxController',
            'bordereaux' => $bordereaux,
            'form' => $form->createView(),
            'retours' => $retours,
            'retourProduits' => $retourProduits,
        ]);
    }
}

templates/liste_bordereaux/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste bordereaux
{% endblock %}

{% block body %}
	{% set csrfTokenDateBordereau = csrf_token('form-date-bordereau') %}
	{% set csrfTokenLierBordereau = csrf_token('form-lier-bordereau') %}
	{% for message in app.flashes('notice') %}
		<div id="message">
			<div class="flash-notice">
				<p class="text-success my-3 fs-3 mx-2 fw-normal text-center">{{ message }}</p>
			</div>
			<div class='d-flex justify-content-center'>
				<button type="submit" class="btn btn-outline-success border-3 rounded-5" onclick="(removeMessage())">
					<span class='fs-3 fw-normal p-3'>OK!</span>
				</button>
			</div>
		</div>
	{% endfor %}
	<h1 class="text-white mx-3 my-5 fs-3 fw-normal text-center">Liste des bordereaux</h1>
	<form method="get" action="{{ path('app_liste_bordereaux') }}">
		<div class="d-flex justify-content-center">
			<div class='border rounded-3 border-warning border-2 m-3 custom-width-desktop'>
				<div class="form-group m-3">
					<label for="date_reception" class='mb-3'>
						<span class='fs-3 fw-normal text-warning'>Date :</span>
					</label>
					<input type="date" name="date_reception" class="form-control fs-3 fw-bold border-dark border-2" id="date_reception"/>
				</div>
				<div class='ms-3 my-4'>
					<button type="submit" class="btn btn-outline-warning border-2 rounded-5">
						<span class='fs-3 fw-normal'>Recherche</span>
					</button>
				</div>
			</div>
		</div>
		<input type="hidden" name="_token" value="{{ csrfTokenDateBordereau }}">
	</form>
	<h2 class="text-white fs-3 mx-3 my-5 fw-normal text-center">Résultats recherche par date</h2>
	{% for bordereau in bordereaux %}
		<div class="d-flex justify-content-center">
			<div class='border-primary border border-2 mx-1 rounded-3 my-3 custom-width-desktop'>
				<div class="d-flex flex-row m-1">
					<div>
						<input class="form-check-input border-primary border-3 p-3 m-0" type="checkbox" id="CheckboxBordereau_{{ bordereau.id }}" onchange='isCheckedBordereau({{ bordereau.id }})' data-id="{{ bordereau.id }}">
					</div>
					<div>
						<label class="form-check-label ms-1" for="CheckboxBordereau_{{ bordereau.id }}">
							<span class='fs-3 fw-normal text-white'>choisir</span>
						</label>
					</div>
				</div>
				<p class='fs-3 fw-normal text-white ms-1'>{{ bordereau.numbordereau }}</p>
				{% if bordereau.photo1 %}
					<div class="d-flex justify-content-center">
						<img width='300px' height='300px' class="mt-2 img-fluid" src="{{ asset(bordereau.photo1) }}"/>
					</div>
					<!-- Bouton pour ouvrir la modal -->
					<div class="d-flex justify-content-center">
						<button type="button" class="btn btn-outline-primary mx-2 my-4 border-2 rounded-5" data-bs-toggle="modal" data-bs-target="#imageModal_{{ bordereau.id }}">
							<span class='fs-3 fw-normal'>Ouvrir l'image</span>
						</button>
					</div>
					<!-- Modal -->
					<div class="modal fade" id="imageModal_{{ bordereau.id }}" tabindex="-1" aria-labelledby="imageModalLabel_{{ bordereau.id }}" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered modal-xl">
							<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title" id="imageModalLabel">Image</h5>
									<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
								</div>
								<div class="modal-body">
									<img class="img-fluid" src="{{ asset(bordereau.photo1) }}" alt="Image">
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
								</div>
							</div>
						</div>
					</div>
				{% endif %}
				{% if bordereau.photo2 %}
					<div>
						<img width='300px' height='300px' class="mt-2 img-fluid" src="{{ asset(bordereau.photo2) }}"/>
					</div>
				{% endif %}
				<p class='fs-3 fw-normal text-white ms-2'>{{ bordereau.commentaire }}</p>
			</div>
		</div>
	{% endfor %}
	<p class="text-white my-5 fs-3 fw-normal text-center">Recherche pour lier un/des attendus ou sans attendus</p>
	<div class="d-flex justify-content-center">
		<div class="border border-2 border-warning mx-1 rounded-4 custom-width-desktop">
			{{ form_start(form) }}
			<div class='m-2'>
				{{ form_label(form.numRetour, 'N° RET, RETSA, NT', {'label_attr': {'class': 'form-label text-warning fs-3 fw-normal'}}) }}
				{{ form_widget(form.numRetour) }}
			</div>
			<div class='m-2'>
				{{ form_label(form.prenomClient, 'Prénom client', {'label_attr': {'class': 'form-label text-warning fs-3 fw-normal'}}) }}
				{{ form_widget(form.prenomClient) }}
			</div>
			<div class='m-2'>
				{{ form_label(form.nomClient, 'Nom client', {'label_attr': {'class': 'form-label text-warning fs-3 fw-normal'}}) }}
				{{ form_widget(form.nomClient) }}
			</div>
			<div class='m-2'>
				{{ form_label(form.transporteur, 'Transporteur', {'label_attr': {'class': 'form-label text-warning fs-3 fw-normal'}}) }}
				{{ form_widget(form.transporteur) }}
			</div>
			<div class='d-flex justify-content-center'>
				<button type="submit" class="btn btn-outline-warning my-3 border-2 rounded-5">
					<span class='fs-3 fw-normal'>Recherche</span>
				</button>
			</div>
			{{ form_end(form) }}
		</div>
	</div>
	<h4 class="text-white fs-3 my-5 fw-normal text-center">liste attendus/sans attendus</h4>
	{% for retour in retours %}
		<div class="d-flex justify-content-center">
			<div class="my-3">
				<div class="custom-width-desktop">
					<div class="card m-1 border-primary border-3">
						<div class="card-body">
							<div class="container p-0 m-0">
								<div class="form-check p-0 m-0 d-flex flex-column">
									<div>
										<input class="form-check-input border-primary border-4 p-3 m-0" type="checkbox" id="CheckboxListe_{{ retour.id }}" onchange='isCheckedListe({{ retour.id }})'>
									</div>
									<div>
										<label class="form-check-label m-0" for="CheckboxListe_{{ retour.id }}">
											<span class='fs-3 fw-normal'>{{ retour.numretour }}</span>
										</label>
									</div>
								</div>
							</div>
							<p class="card-text m-0">
								<span class='fs-3 fw-normal'>{{ retour.prenomclient}}
									{{ retour.nomclient}}</span>
							</p>
							<p class="card-text m-0">
								<span class='fs-3 fw-normal'>{{ retour.Transporteur }}</span>
							</p>
							{% for retourProduit in retour.retourProduits %}
								<p class="card-text m-0">
									<span class='fs-3 fw-normal'>{{ retourProduit.idproduit }}
										*
										{{ retourProduit.quantite }}</span>
								</p>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endfor %}
	<form method="get" action="{{ path('app_liste_bordereaux') }}" id="lienForm">
		<div class='my-5 d-flex justify-content-center'>
			<button type="submit" class="btn btn-outline-warning my-3 border-2 rounded-5">
				<span class='fs-3 fw-normal'>Lier le bordereau</span>
			</button>
		</div>
		<input type="hidden" name="_token" value="{{ csrfTokenLierBordereau }}">
	</form>

	<script type="text/javascript">

		function isCheckedBordereau(id) {

let checkbox = document.getElementById('CheckboxBordereau_' + id);

// Désélectionner toutes les autres cases à cocher
let checkboxes = document.querySelectorAll('input[type="checkbox"][id^="CheckboxBordereau_"]');
checkboxes.forEach(function (otherCheckbox) {
if (otherCheckbox !== checkbox) {
otherCheckbox.checked = false;
// Supprimer le champ de formulaire hidden correspondant
let hiddenInput = document.getElementById('HiddenInputBordereau_' + otherCheckbox.dataset.id);
if (hiddenInput) {
hiddenInput.remove();
}
}
});

// Vérifier si la case à cocher est cochée
if (checkbox.checked) { // Ajouter un champ de formulaire hidden au formulaire avec l'ID sélectionné
let form = document.getElementById('lienForm');
let input = document.createElement('input');
input.type = 'hidden';
input.name = 'bordereau'; // Nom du champ dans le formulaire
input.value = id;
input.id = 'HiddenInputBordereau_' + id; // Ajouter un ID pour pouvoir le supprimer si nécessaire
form.appendChild(input);
} else { // Supprimer le champ de formulaire hidden si la case à cocher est désélectionnée
let hiddenInput = document.getElementById('HiddenInputBordereau_' + id);
if (hiddenInput) {
hiddenInput.remove();
}
}
}
function isCheckedListe(id) {

let checkbox = document.getElementById('CheckboxListe_' + id);

// Vérifier si la case à cocher est cochée
if (checkbox.checked) { // Ajouter un champ de formulaire hidden au formulaire avec l'ID sélectionné
let form = document.getElementById('lienForm');
let input = document.createElement('input');
input.type = 'hidden';
input.name = 'liste[]'; // Nom du champ dans le formulaire
input.value = id;
input.id = 'HiddenInputListe_' + id; // Ajouter un ID pour pouvoir le supprimer si nécessaire
form.appendChild(input);
} else { // Supprimer le champ de formulaire hidden si la case à cocher est désélectionnée
let hiddenInput = document.getElementById('HiddenInputListe_' + id);
if (hiddenInput) {
hiddenInput.remove();
}
}
}

function removeMessage() {
var eltMessage = document.querySelector('#message')
eltMessage.remove()
}
	</script>
{% endblock %}