src/Entity/Stock.php
<?php

namespace App\Entity;

use App\Repository\StockRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StockRepository::class)]
class Stock
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_produit = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $quantite = null;

    #[ORM\Column(length: 10)]
    private ?string $code_couleur = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_reception = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduit(): ?int
    {
        return $this->id_produit;
    }

    public function setIdProduit(int $id_produit): static
    {
        $this->id_produit = $id_produit;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getCodeCouleur(): ?string
    {
        return $this->code_couleur;
    }

    public function setCodeCouleur(string $code_couleur): static
    {
        $this->code_couleur = $code_couleur;

        return $this;
    }

    public function getDateReception(): ?\DateTimeInterface
    {
        return $this->date_reception;
    }

    public function setDateReception(?\DateTimeInterface $date_reception): static
    {
        $this->date_reception = $date_reception;

        return $this;
    }
}

src/Controller/ListeStockController.php
<?php

namespace App\Controller;

use App\Entity\Stock;
use App\Entity\Palette;
use App\Entity\PaletteProduit;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ListeStockController extends AbstractController
{
    private $csrfTokenManager;

    public function __construct(CsrfTokenManagerInterface $csrfTokenManager)
    {
        $this->csrfTokenManager = $csrfTokenManager;
    }

    #[IsGranted("ROLE_USER")]
    #[Route('/liste/stock', name: 'app_liste_stock')]
    public function index(Request $request, EntityManagerInterface $entityManager): Response
    {

        $produitsPalettes = $entityManager->getRepository(PaletteProduit::class)->findAll();
        foreach ($produitsPalettes as $produitPalette) {
            $palette = $produitPalette->getPalette();
        }
        $palettes = $entityManager->getRepository(Palette::class)->findAll();

        if (!empty($request)) {

            $idProduitStock = $request->query->get('recherche-stock-id-produit');
            $couleurProduitStock = $request->query->get('recherche-stock-code-couleur');
            $dateReceptionProduitStock = $request->query->get('recherche-stock-date-reception');

            $criteria = [];

            if ($idProduitStock) {
                $criteria['id_produit'] = $idProduitStock;
                $produitsPalettes = $entityManager->getRepository(PaletteProduit::class)->findByCriteria($criteria);
            }
            if ($couleurProduitStock) {
                $criteria['code_couleur'] = $couleurProduitStock;
                $produitsPalettes = $entityManager->getRepository(PaletteProduit::class)->findByCriteria($criteria);
            }
            if ($dateReceptionProduitStock) {
                $dateTime = new \DateTime($dateReceptionProduitStock);
                $formattedDate = $dateTime->format('Y-m-d H:i:s');
                $criteria['date_reception'] = $formattedDate;
                $produitsPalettes = $entityManager->getRepository(PaletteProduit::class)->findByDate($criteria);
            }
        }

        if (!empty($request->query->get('id-produit-form-modif-palette'))) {

            $idProduitAModifier = $request->query->get('id-produit-form-modif-palette');
            $ProduitAModifier = $entityManager->getRepository(PaletteProduit::class)->find($idProduitAModifier);
            

            for ($p = $ProduitAModifier->getQuantite(); $p >= 1; $p--) {

                $paletteProduit = new PaletteProduit();
                $paletteId = $request->query->get('form-modif-palette_' . $p);
                $palette = $entityManager->getRepository(Palette::class)->find($paletteId);
                $codeCouleur = $palette->getCodeCouleur();
                $paletteProduit->setPalette($palette);
                $paletteProduit->setIdProduit($ProduitAModifier->getIdProduit());
                $paletteProduit->setQuantite(1);
                $paletteProduit->setCodeCouleur($codeCouleur);
                $currentDate = new \DateTime();
                $paletteProduit->setDateReception($currentDate);
                $entityManager->persist($paletteProduit);
                $entityManager->flush();
            }

            $entityManager->remove($ProduitAModifier);
            $entityManager->flush();
        }

        $csrfTokenProduitStock = $this->csrfTokenManager->getToken('form-stock');

        return $this->render('liste_stock/index.html.twig', [
            'controller_name' => 'ListeStockController',
            'produitsPalettes' => $produitsPalettes,
            'palette' => $palette,
            'palettes' => $palettes
        ]);
    }
}

templates/liste_stock/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste du Stock
{% endblock %}

{% block body %}
	{% set csrfTokenStock = csrf_token('form-stock') %}
	<h1 class="text-white my-5 fs-1 fw-normal text-center">Liste du stock</h1>
	<div class="border border-2 border-light rounded-3 mx-2 my-5">
		<h2 class="text-white my-5 fs-1 fw-bold text-center">Import du stock</h2>
		<a class='text-white m-3'>lien vers le modèle</a>
		<div class="form-group m-3">
			<div class="input-group">
				<div class="custom-file">
					<input type="file" class="form-control text-light" id="exampleFile" aria-describedby="fileHelp"/>
				</div>
				<p id="fileHelp" class="text-light">Format pris en charge csv.</p>
			</div>
		</div>
	</div>
	<div class="d-flex justify-content-center">
		<div class='border rounded-3 border-warning border-2 mx-2 my-5 input-desktop'>
			<form method="get" action="{{ path('app_liste_stock') }}">
				<div class="form-group m-3">
					<label for="recherche-stock-code-couleur" class="form-label">
						<span class='fs-3 fw-normal text-warning'>Code couleur :</span>
					</label>
					<select class="form-select fs-3 fw-normal border-dark border-2" id="recherche-stock-code-couleur" name="recherche-stock-code-couleur">
						<option value="" class='fs-3 fw-normal'>choisir</option>
						<option value="vert" class='fs-3 fw-normal'>vert</option>
						<option value="jaune" class='fs-3 fw-normal'>jaune</option>
						<option value="orange" class='fs-3 fw-normal'>orange</option>
						<option value="rouge" class='fs-3 fw-normal'>rouge</option>
						<option value="noir" class='fs-3 fw-normal'>noir</option>
					</select>
				</div>
				<div class="form-group m-3">
					<label for="recherche-stock-id-produit" class="form-label">
						<span class='fs-3 fw-normal text-warning'>ID produit :</span>
					</label>
					<input type="text" class="form-control fs-3 fw-normal border-dark border-2" id="recherche-stock-id-produit" placeholder="ID" name="recherche-stock-id-produit">
				</div>
				<div class="form-group m-3">
					<label for="recherche-stock-date-reception" class="form-label">
						<span class='fs-3 fw-normal text-warning'>Date :</span>
					</label>
					<input type="date" name="recherche-stock-date-reception" class="form-control fs-3 fw-normal border-dark border-2" id="recherche-stock-date-reception"/>
				</div>
				<div class='d-flex justify-content-center mb-4'>
					<button type="submit" class="btn btn-outline-warning my-2 border-2 rounded-5">
						<span class='fs-2 fw-normal'>Rechercher</span>
					</button>
				</div>
				<input type="hidden" name="_token" value="{{ csrfTokenStock }}">
			</form>
		</div>
	</div>
	<h4 class="text-white my-5 fs-1 fw-normal text-center mx-1">Résultat de la recherche</h4>
	<div class="d-flex justify-content-center mb-5">
		<div>
			<div class="d-flex flex-column">
				{% for produitPalette in produitsPalettes %}
					<form method="get" action="{{ path('app_liste_stock') }}">
						<div class="card my-4 border-primary border-3 custom-width-desktop">
							<div class="card-body p-0 ps-2">
								<p class="card-text m-0">
									<span class='fs-3 fw-bold'>{{ produitPalette.idProduit }}
										*
										{{ produitPalette.quantite }}</span>
								</p>
								<p class="card-text m-0">
									<span class='fs-3 fw-bold'>{{ produitPalette.dateReception|date('d/m/Y H:i:s') }}</span>
								</p>
								<p class="card-text m-0">
									<span class='fs-3 fw-bold'>palette N°{{ produitPalette.getPalette() }}
										-
										{{ produitPalette.codeCouleur }}</span>
								</p>
								<p class="card-text m-0 fs-3">Modification palettes</p>
								{% for i in 1..produitPalette.quantite %}
									<div class="m-3">
										<label for="form-modif-palette_{{ i }}" class="form-label">
											<span class='fs-3 fw-normal'>Palette produit
												{{ i }}</span>
										</label>
										<select class="form-select w-100 fs-3 fw-normal border-dark border-3 rounded-3" id="form-modif-palette_{{ i }}" name="form-modif-palette_{{ i }}" required>
											<option value="{{ produitPalette.getPalette() }}" class='fs-3 fw-normal'>N°{{ produitPalette.getPalette() }}
												{{ produitPalette.codeCouleur }}</option>
											{% for palette in palettes %}
												<option value="{{ palette.id }}" class='fs-3 fw-normal'>N°{{ palette.id }}
													{{ palette.codeCouleur }}</option>
											{% endfor %}
										</select>
									</div>
								{% endfor %}
								<div class='d-flex justify-content-center mb-2'>
									<button type="submit" class="btn btn-outline-primary my-2 border-2 rounded-5">
										<span class='fs-3 fw-normal'>Modifier</span>
									</button>
								</div>
							</div>
						</div>
						<input type="hidden" value="{{ produitPalette.id }}" name="id-produit-form-modif-palette"/>
					</form>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}