src/Entity/Palette.php
<?php

namespace App\Entity;

use App\Repository\PaletteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PaletteRepository::class)]
class Palette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $code_couleur = null;

    #[ORM\Column(length: 15, nullable: true)]
    private ?string $depot = null;

    #[ORM\OneToMany(mappedBy: 'palette', targetEntity: PaletteProduit::class)]
    private Collection $paletteProduits;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_termine = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_transmise = null;

    #[ORM\Column(length: 20, nullable: true)]
    private ?string $statut = null;

    public function __construct()
    {
        $this->paletteProduits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeCouleur(): ?string
    {
        return $this->code_couleur;
    }

    public function setCodeCouleur(?string $code_couleur): static
    {
        $this->code_couleur = $code_couleur;

        return $this;
    }

    public function getDepot(): ?string
    {
        return $this->depot;
    }

    public function setDepot(?string $depot): static
    {
        $this->depot = $depot;

        return $this;
    }

    /**
     * @return Collection<int, PaletteProduit>
     */
    public function getPaletteProduits(): Collection
    {
        return $this->paletteProduits;
    }

    public function addPaletteProduit(PaletteProduit $paletteProduit): static
    {
        if (!$this->paletteProduits->contains($paletteProduit)) {
            $this->paletteProduits->add($paletteProduit);
            $paletteProduit->setPalette($this);
        }

        return $this;
    }

    public function removePaletteProduit(PaletteProduit $paletteProduit): static
    {
        if ($this->paletteProduits->removeElement($paletteProduit)) {
            // set the owning side to null (unless already changed)
            if ($paletteProduit->getPalette() === $this) {
                $paletteProduit->setPalette(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->id;
    }

    public function getDateTermine(): ?\DateTimeInterface
    {
        return $this->date_termine;
    }

    public function setDateTermine(?\DateTimeInterface $date_termine): static
    {
        $this->date_termine = $date_termine;

        return $this;
    }

    public function getDateTransmise(): ?\DateTimeInterface
    {
        return $this->date_transmise;
    }

    public function setDateTransmise(?\DateTimeInterface $date_transmise): static
    {
        $this->date_transmise = $date_transmise;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }
}

src/Entity/Stock.php
<?php

namespace App\Entity;

use App\Repository\StockRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StockRepository::class)]
class Stock
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_produit = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $quantite = null;

    #[ORM\Column(length: 10)]
    private ?string $code_couleur = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_reception = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduit(): ?int
    {
        return $this->id_produit;
    }

    public function setIdProduit(int $id_produit): static
    {
        $this->id_produit = $id_produit;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getCodeCouleur(): ?string
    {
        return $this->code_couleur;
    }

    public function setCodeCouleur(string $code_couleur): static
    {
        $this->code_couleur = $code_couleur;

        return $this;
    }

    public function getDateReception(): ?\DateTimeInterface
    {
        return $this->date_reception;
    }

    public function setDateReception(?\DateTimeInterface $date_reception): static
    {
        $this->date_reception = $date_reception;

        return $this;
    }
}

src/Controller/ListePalettesController.php
<?php

namespace App\Controller;

use App\Entity\Palette;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ListePalettesController extends AbstractController
{
    #[Route('/liste/palettes', name: 'app_liste_palettes')]
    public function index(Request $request, EntityManagerInterface $entityManager): Response
    {

        $palettes = $entityManager->getRepository(Palette::class)->findAll();

        if (!empty($request->query->get('recherche-palette')) || !empty($request->query->get('recherche-statut'))) {

            $idPalette = $request->query->get('recherche-palette');
            $statutPalette = $request->query->get('recherche-statut');

            $criteria = [];

            if ($idPalette) {
                $criteria['id'] = $idPalette;
                $palettes = $entityManager->getRepository(Palette::class)->findByCriteria($criteria);
            }

            if ($statutPalette) {
                $criteria['statut'] = $statutPalette;
                $palettes = $entityManager->getRepository(Palette::class)->findByCriteria($criteria);
            }
            
        }
        
        return $this->render('liste_palettes/index.html.twig', [
            'controller_name' => 'ListePalettesController',
            'palettes' => $palettes,
        ]);
    }
}

templates/liste_palettes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Palettes
{% endblock %}

{% block body %}
	{% for message in app.flashes('notice') %}
		<div id="message">
			<div class="flash-notice">
				<p class="text-success my-3 fs-3 mx-2 fw-normal text-center">{{ message }}</p>
			</div>
			<div class='d-flex justify-content-center'>
				<button type="submit" class="btn btn-outline-success border-3 rounded-5" onclick="(removeMessage())">
					<span class='fs-3 fw-normal p-2'>OK!</span>
				</button>
			</div>
		</div>
	{% endfor %}
	<h1 class="text-white my-5 mx-2 fs-3 fw-normal text-center">Liste des palettes</h1>
	<div class="d-flex justify-content-center">
		<div class='border rounded-3 border-warning border-2 mx-2 input-desktop'>
			<form method="get" action="{{ path('app_liste_palettes') }}">
				<div class="form-group m-3">
					<label for="recherche-palette" class="form-label">
						<span class='fs-3 fw-normal text-warning'>N° :</span>
					</label>
					<input type="text" class="form-control fs-3 fw-normal border-dark border-2" id="recherche-palette" placeholder="palette" name="recherche-palette">
				</div>
				<div class="form-group m-3">
					<label for="recherche-statut" class="form-label">
						<span class='fs-3 fw-normal text-warning'>Statut :</span>
					</label>
					<select class="form-select fs-3 fw-normal border-dark border-3 rounded-3" id="recherche-statut" name="recherche-statut">
						<option value="" class='fs-3 fw-normal'>choisir</option>
						<option value="en-cours" class='fs-3 fw-normal'>en cours</option>
						<option value="termine" class='fs-3 fw-normal'>terminée</option>
						<option value="transmise" class='fs-3 fw-normal'>transmise</option>
					</select>
				</div>
				<div class='d-flex justify-content-center mb-4'>
					<button type="submit" class="btn btn-outline-warning my-2 border-2 rounded-5">
						<span class='fs-3 fw-normal'>Rechercher</span>
					</button>
				</div>
			</form>
		</div>
	</div>
	{% for palette in palettes %}
		<form method="post" class="card my-5 mx-1 border-primary border-3" action="{{ path('app_pdf') }}">
			<div class="card-body p-2 custom-width-desktop">
				<p class='fs-3 fw-normal my-3'>Palette N°
					{{ palette.id }}
					{{ palette.codeCouleur }}</p>

				{% if palette.dateTransmise is not null %}
					<p class='fs-3 fw-normal my-3'>transmise le :
						{{ palette.dateTransmise|date('d/m/Y H:i:s') }}</p>
				{% elseif palette.dateTermine is not null %}
					<p class='fs-3 fw-normal my-3'>terminée le :
						{{ palette.dateTermine|date('d/m/Y H:i:s') }}</p>
				{% else %}
					<p class='fs-3 fw-normal my-3'>toujours en cours</p>
				{% endif %}
				<input type="hidden" value="{{ palette.id }}" name="numero-palette-pdf"/>
				<div class="form-group">
					<label for="fixer-statut" class="form-label">
						<span class='fs-3 fw-normal'>Statut :</span>
					</label>
					<select class="form-select fs-3 fw-normal border-primary border-2 rounded-3" id="fixer-statut" name="fixer-statut">
						<option value="{{ palette.statut }}" class='fs-3 fw-normal'>{{ palette.statut }}</option>
						<option value="en cours" class='fs-3 fw-normal'>en cours</option>
						<option value="terminée" class='fs-3 fw-normal'>terminée</option>
						<option value="transmise" class='fs-3 fw-normal'>transmise</option>
					</select>
				</div>
				<div class="form-group">
					<label for="fixer-depot" class="form-label my-3">
						<span class='fs-3 fw-normal'>Dépot :</span>
					</label>
					<select class="form-select fs-3 fw-normal border-primary border-2 rounded-3" id="fixer-depot" name="fixer-depot">
						<option value="{{ palette.depot }}" class='fs-3 fw-normal'>{{ palette.depot }}</option>
						<option value="sans dépot" class='fs-3 fw-normal'>sans dépot</option>
						<option value="phyléa" class='fs-3 fw-normal'>phyléa</option>
						<option value="abérial" class='fs-3 fw-normal'>abérial</option>
					</select>
				</div>
				<input type="hidden" value="{{ palette.codeCouleur }}" name="pdf-code-couleur"/>
				<p class='fs-3 fw-normal my-2'>Produits * Quantité :</p>
				{% for produitPalette in palette.getPaletteProduits %}
					<input type="hidden" value="{{ produitPalette.idProduit }}" name="pdf-id-produit[]"/>
					<input type="hidden" value="{{ produitPalette.quantite }}" name="pdf-quantite[]"/>
					<p class='fs-3 fw-normal my-2'>-
						{{ produitPalette.idProduit }}
						*
						{{ produitPalette.quantite }}</p>
				{% endfor %}
				<div class='my-4 d-flex justify-content-center'>
					<button type="submit" class="btn btn-outline-primary border-2 rounded-5">
						<span class='fs-3 fw-normal'>Valider</span>
					</button>
				</div>
			</div>
		</form>
	{% endfor %}
    <script type="text/javascript">
function removeMessage() {
var eltMessage = document.querySelector('#message')
eltMessage.remove()
}
</script>
{% endblock %}